name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]  # O la rama que prefieras

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
      
    - name: Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Buscar docker-compose.yml
      run: |
        echo "Buscando docker-compose.yml en todo el repositorio:"
        find . -name docker-compose.yml
        
    - name: Construir y subir imagen de Docker Compose
      run: |
        COMPOSE_FILE=$(find . -name docker-compose.yml | head -n 1)
        if [ -n "$COMPOSE_FILE" ]; then
          echo "Archivo docker-compose.yml encontrado en: $COMPOSE_FILE"
          docker-compose -f "$COMPOSE_FILE" build
          docker-compose -f "$COMPOSE_FILE" push
        else
          echo "Error: docker-compose.yml no encontrado en el repositorio"
          exit 1
        fi
    
        